### ISSUE TITLE
Its... crashing?

### ISSUE THREAD

**Issue by Merith-TK** [The-Tiny-Taters/packwiz-server-updater#1]
```
[04:24:39] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.7
[04:24:40] [main/INFO]: Loading 6 mods:
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.20.1
	- packwizsu 2.1.1
	   \-- com_moandjiezana_toml_toml4j 0.7.2
[04:24:40] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[04:24:40] [main/INFO]: Compatibility level set to JAVA_17
[04:24:44] [main/INFO]: Packwiz Server Updater loaded without a pack.toml file to update from
[04:24:44] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:24:45] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[04:24:46] [main/INFO]: Loaded 7 recipes
[04:24:46] [main/INFO]: Loaded 1271 advancements
[04:24:47] [Server thread/INFO]: Starting minecraft server version 1.20.1
[04:24:47] [Server thread/INFO]: Loading properties
[04:24:47] [Server thread/INFO]: Default game type: SURVIVAL
[04:24:47] [Server thread/INFO]: Generating keypair
[04:24:47] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25982
[04:24:47] [Server thread/INFO]: Using epoll channel type
[04:24:47] [Server thread/INFO]: Preparing level "world"
[04:24:52] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:55] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:56] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:56] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[04:24:57] [Server thread/INFO]: Time elapsed: 4791 ms
[04:24:57] [Server thread/INFO]: Done (9.750s)! For help, type "help"
[04:25:57] [Server Watchdog/ERROR]: A single server tick took 60.00 seconds (should be max 0.05)
[04:25:57] [Server Watchdog/ERROR]: Considering it to be crashed, server will forcibly shutdown.
[04:25:57] [Server Watchdog/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-03-14_04.25.57-server.txt
```
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-03-14 04:25:57
Description: Watching Server

java.lang.Error: Watchdog
	at java.base@17.0.10/sun.nio.ch.Net.connect0(Native Method)
	at java.base@17.0.10/sun.nio.ch.Net.connect(Net.java:579)
	at java.base@17.0.10/sun.nio.ch.Net.connect(Net.java:568)
	at java.base@17.0.10/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base@17.0.10/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base@17.0.10/java.net.Socket.connect(Socket.java:633)
	at java.base@17.0.10/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base@17.0.10/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base@17.0.10/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base@17.0.10/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base@17.0.10/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base@17.0.10/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base@17.0.10/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base@17.0.10/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base@17.0.10/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base@17.0.10/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at ttt.packwizsu.command.PackwizsuCommands.testPackTomlLink(PackwizsuCommands.java:128)
	at ttt.packwizsu.command.PackwizsuCommands.setTomlLink(PackwizsuCommands.java:65)
	at ttt.packwizsu.command.PackwizsuCommands$$Lambda$4373/0x00007f82c098cba0.run(Unknown Source)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	at net.minecraft.class_2170.method_9249(class_2170.java:287)
	at net.minecraft.class_2170.method_44252(class_2170.java:280)
	at net.minecraft.class_3176.method_13941(class_3176.java:299)
	at net.minecraft.class_3176.method_3813(class_3176.java:284)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at net.minecraft.server.MinecraftServer$$Lambda$4650/0x00007f82c09e6000.run(Unknown Source)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server Watchdog
Stacktrace:
	at java.base@17.0.10/sun.nio.ch.Net.connect0(Native Method)
	at java.base@17.0.10/sun.nio.ch.Net.connect(Net.java:579)
	at java.base@17.0.10/sun.nio.ch.Net.connect(Net.java:568)
	at java.base@17.0.10/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base@17.0.10/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base@17.0.10/java.net.Socket.connect(Socket.java:633)
	at java.base@17.0.10/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base@17.0.10/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base@17.0.10/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base@17.0.10/sun.net.www.http.HttpClient.openServer(HttpClient.java:533)
	at java.base@17.0.10/sun.net.www.http.HttpClient.openServer(HttpClient.java:638)
	at java.base@17.0.10/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base@17.0.10/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base@17.0.10/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base@17.0.10/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base@17.0.10/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base@17.0.10/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at ttt.packwizsu.command.PackwizsuCommands.testPackTomlLink(PackwizsuCommands.java:128)
	at ttt.packwizsu.command.PackwizsuCommands.setTomlLink(PackwizsuCommands.java:65)
	at ttt.packwizsu.command.PackwizsuCommands$$Lambda$4373/0x00007f82c098cba0.run(Unknown Source)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	at net.minecraft.class_2170.method_9249(class_2170.java:287)
	at net.minecraft.class_2170.method_44252(class_2170.java:280)
	at net.minecraft.class_3176.method_13941(class_3176.java:299)
	at net.minecraft.class_3176.method_3813(class_3176.java:284)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)

-- Thread Dump --
Details:
	Threads: "Reference Handler" daemon prio=10 Id=2 RUNNABLE
	at java.base@17.0.10/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@17.0.10/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
	at java.base@17.0.10/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)


"Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@7d22ee19
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@7d22ee19
	at java.base@17.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at java.base@17.0.10/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)


"Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE


"Notification Thread" daemon prio=9 Id=10 RUNNABLE


"Common-Cleaner" daemon prio=8 Id=11 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@73e51fcd
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@73e51fcd
	at java.base@17.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.10/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
	at java.base@17.0.10/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)


"JNA Cleaner" daemon prio=5 Id=21 WAITING on java.lang.ref.ReferenceQueue$Lock@77da8569
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@77da8569
	at java.base@17.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	at java.base@17.0.10/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	at com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)


"Timer hack thread" daemon prio=5 Id=22 TIMED_WAITING
	at java.base@17.0.10/java.lang.Thread.sleep(Native Method)
	at net.minecraft.class_156$9.run(class_156.java:839)


"Yggdrasil Key Fetcher" daemon prio=5 Id=23 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@32d815f6
	at java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@32d815f6
	at java.base@17.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.10/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1672)
	at java.base@17.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
	at java.base@17.0.10/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.10/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	...


"Server thread" prio=5 Id=27 RUNNABLE (in native)
	at java.base@17.0.10/sun.nio.ch.Net.connect0(Native Method)
	at java.base@17.0.10/sun.nio.ch.Net.connect(Net.java:579)
	at java.base@17.0.10/sun.nio.ch.Net.connect(Net.java:568)
	at java.base@17.0.10/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base@17.0.10/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base@17.0.10/java.net.Socket.connect(Socket.java:633)
	at java.base@17.0.10/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base@17.0.10/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	...

	Number of locked synchronizers = 3
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@58e07792
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@3200034
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@20f23cf4


"DestroyJavaVM" prio=5 Id=29 RUNNABLE


"Server console handler" daemon prio=5 Id=30 RUNNABLE (in native)
	at java.base@17.0.10/java.io.FileInputStream.readBytes(Native Method)
	at java.base@17.0.10/java.io.FileInputStream.read(FileInputStream.java:276)
	at java.base@17.0.10/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
	at java.base@17.0.10/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	-  locked java.io.BufferedInputStream@52f7eab9
	at java.base@17.0.10/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
	at java.base@17.0.10/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
	at java.base@17.0.10/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
	-  locked java.io.InputStreamReader@9705b92
	at java.base@17.0.10/java.io.InputStreamReader.read(InputStreamReader.java:177)
	...


"Netty Epoll Server IO #0" daemon prio=5 Id=31 RUNNABLE (in native)
	at io.netty.channel.epoll.Native.epollWait(Native Method)
	at io.netty.channel.epoll.Native.epollWait(Native.java:209)
	at io.netty.channel.epoll.Native.epollWait(Native.java:202)
	at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:306)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:363)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)


"Server Watchdog" daemon prio=5 Id=36 RUNNABLE
	at java.management@17.0.10/sun.management.ThreadImpl.dumpThreads0(Native Method)
	at java.management@17.0.10/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:521)
	at java.management@17.0.10/sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:509)
	at net.minecraft.class_3178.run(class_3178.java:47)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)



Stacktrace:
	at net.minecraft.class_3178.run(class_3178.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)

-- Performance stats --
Details:
	Random tick rate: 3
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 0, entities: 156,156,61,441,441,0,0 [minecraft:falling_block:55,minecraft:pig:26,minecraft:chest_minecart:18,minecraft:cow:18,minecraft:sheep:14], block_entities: 58 [minecraft:sculk_sensor:34,minecraft:mob_spawner:11,minecraft:sculk_catalyst:9,minecraft:beehive:3,minecraft:sculk_shrieker:1], block_ticks: 11423, fluid_ticks: 129, chunk_source: Chunks[S] W: 2209 E: 156,156,61,441,441,0,0,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 0,0,0,0,0,0,0 [], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: Chunks[S] W: 0 E: 0,0,0,0,0,0,0

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-79-generic
	Java Version: 17.0.10, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1624987520 bytes (1549 MiB) / 2323644416 bytes (2216 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 7600 6-Core Processor
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 141257.34
	Virtual memory used (MB): 182173.13
	Swap memory total (MB): 45055.99
	Swap memory used (MB): 20483.80
	JVM Flags: 2 total; -Xms128M -Xmx6144M
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
	```

**Comment by EvieTheOwl** [comment]
Sorry for the late reply. It looks like maybe a network security / firewall issue. I'll add an extra catch clause in the next update to catch any unexpected errors if this keeps happening.
